baseURL = "https://cyberform.org/"
title = "CyberForge – Hacker's Vault"
languageCode = "en-us"
theme = "cyberpunk"
paginate = 25
enableRobotsTXT = true

[params]
  author = "CyberForge Crew"
  description = "Auto-updating arsenal for Black, Grey, and White Hat hackers."
  themeColor = "#33FF33"
  defaultImage = "https://cyberform.org/images/og-default.png"

[outputs]
  home = ["HTML","RSS"]

[taxonomies]
  category = "categories"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Tools"
    url = "/tools/"
    weight = 2
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3

# (Optional) control trailing slash if you need:
trailingSlash = "never"
