baseURL = "https://cyberform.org/"
title = "Cyberforge – Hacker's Vault"
languageCode = "en-us"
theme = "ananke"
paginate = 25
enableRobotsTXT = true

[params]
  author = "Cyberforge Crew"
  description = "Auto-updating arsenal for Black, Grey, and White Hat hackers."
  themeColor = "#33FF33"

[outputs]
  home = ["HTML","RSS"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Tools"
    url = "/tools/"
    weight = 2
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
    
