name: Auto-update sources

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight

jobs:
  update_sources:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scraper/requirements.txt

    - name: Run scraper and generate sources
      env:
        CYBERFORGE_GH_TOKEN: ${{ secrets.CYBERFORGE_GH_TOKEN }}  # Pass the token here
      run: |
        python scraper/generate_sources.py

    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.CYBERFORGE_GH_TOKEN }}  # Pass the token for git push
      run: |
        git add scraper/sources.txt
        git diff --quiet || git commit -m "Auto-update sources by GitHub Actions"
        git push https://x-access-token:${GH_TOKEN}@github.com/KomaVR/CYBER-FORGE.git HEAD:main
