name: Build & Deploy Hugo Site

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *'  # Daily deploy at 3 AM UTC
  workflow_dispatch:     # <-- THIS adds the Deploy Now button

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: |
          cd scraper
          pip install -r requirements.txt

      - name: Run Fixer Script (Fix Broken Files)
        run: |
          cd scraper
          python3 fix_filenames_and_frontmatter.py

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.104.2'

      - name: Build Hugo Site
        run: |
          cd site
          hugo || echo "Hugo build failed but continuing deployment..."

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./site/public
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: cyberform.org
