name: Auto Build & Deploy

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *'  # daily at 3AM UTC

permissions:
  contents: write  # Needed to push to gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: |
          cd scraper
          pip install -r requirements.txt
          pip install lxml

      - name: Scrape and Generate Content
        run: |
          cd scraper
          python scrape.py
          python classify.py
          python generate_hugo_content.py

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.111.3'

      - name: Build Hugo Site
        run: |
          cd site
          hugo

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.CYBERFORGE_GH_TOKEN }}
          publish_dir: ./site/public
          publish_branch: gh-pages
